server:
  port: 8081


spring:
  datasource: 
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/db_fornecedor?serverTimezone=UTC
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB10Dialect

  